# Generated by Django 6.0.5 on 2026-05-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='hls_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
