# Generated by Django 6.0.5 on 2026-05-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_videofile_hls_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='hls_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
