# Generated by Django 6.0.5 on 2026-05-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_remove_video_duration_remove_video_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
