# Generated by Django 6.0.5 on 2026-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0003_alter_videofile_hls_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='format',
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
