# Generated by Django 6.0.4 on 2026-05-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0004_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
    ]
