# Generated by Django 6.0.4 on 2026-05-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0005_rename_thumbnail_video_thumbnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
